# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "dirigiblelabs/buildpacks-xsk-cf"
version = "#{XSKVersion}#"
name = "XSK Cloud Foundry Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "com.sap.kneo.xsk"
