# Buildpacks to include in builder
[[buildpacks]]
uri = "."

[[order]]
    [[order.group]]
    id = "dirigiblelabs/buildpacks-xsk"
    version = "#{XSKVersion}#"

[stack]
id = "com.sap.kneo.xsk"
build-image = "dirigiblelabs/buildpacks-stack-build-xsk:#{XSKVersion}#"
run-image = "dirigiblelabs/buildpacks-stack-run-xsk:#{XSKVersion}#"
