{{- if ne .Values.create.namespace "default" }}
apiVersion: v1
kind: Namespace
metadata:
    name: {{ required "Missing namespace" .Values.create.namespace }}
{{- end }}  
---
{{- if or .Values.install.clusterBuilder .Values.install.allInOne }}
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: {{ required "Missing docker secret name" .Values.docker.secretName }}
  namespace: {{ required "Missing namespace" .Values.create.namespace }}
type: kubernetes.io/dockerconfigjson    
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "Missing docker service account name" .Values.docker.serviceAccountName }}
  namespace: {{ required "Missing namespace" .Values.create.namespace }}
imagePullSecrets:
- name: {{ required "Missing docker secret name" .Values.docker.secretName }}
secrets:
- name: {{ required "Missing docker secret name" .Values.docker.secretName }}
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: kneo-xsk-store
  namespace: {{ required "Missing namespace" .Values.create.namespace }}
spec:
  sources:
  - image: "{{ required "Missing image builder buildpack" .Values.imageBuilder.buildpack }}:#{XSKVersion}#"
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: kneo-xsk-stack
  namespace: {{ required "Missing namespace" .Values.create.namespace }}
spec:
  id: com.sap.kneo.xsk
  buildImage:
    image: {{ required "Missing cluster build image" .Values.clusterBuilder.buildImage }}
  runImage:
    image: {{ required "Missing cluster run image" .Values.clusterBuilder.runImage }}
{{- end }}
---
{{- if or .Values.install.imageBuilder .Values.install.allInOne}}
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: kneo-xsk
  namespace: {{ required "Missing namespace" .Values.create.namespace }}
spec:
  serviceAccount: {{ required "Missing service account name" .Values.clusterBuilder.serviceAccountName }}
  tag: {{ required "Missing imageBuilder repository" .Values.imageBuilder.repository }}
  stack:
    name: kneo-xsk-stack
    kind: ClusterStack
  store:
    name: kneo-xsk-store
    kind: ClusterStore
  order:
  - group:
    - id: {{ required "Missing buildpack image" .Values.imageBuilder.buildpack }}
{{- end }}
---
{{- if or .Values.create.image .Values.install.allInOne }}
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: {{ required "Missing release name" .Release.Name }}
  namespace: {{ required "Missing namespace" .Values.create.namespace }}
spec:
  tag: {{ required "Missing image repository" .Values.image.repository }}
  serviceAccount: {{ required "Missing service account name" .Values.image.serviceAccountName }}
  builder:
    name: kneo-xsk
    kind: Builder
  source:
    blob:
      url: {{ required "Missing image source" .Values.image.source }}
{{- end }}