name: Deploy Application Image

on:
  workflow_dispatch:
    inputs:
      applicationRepository:
        description: Application Repository
        required: true
        default: 'thuf/test-xsjs-2'
      applicationReleaseVersion:
        description: Application Release Version
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kube Config File
        env:
          KYMA_CERTIFICATE: ${{ secrets.KYMA_CERTIFICATE }}
          KYMA_SERVER: ${{ secrets.KYMA_SERVER }}
          KYMA_TOKEN: ${{ secrets.KYMA_TOKEN }}
        run: |
          mkdir $HOME/.kube
          echo "
          apiVersion: v1
          kind: Config
          current-context: xsk
          clusters:
          - name: xsk
            cluster:
              certificate-authority-data: $KYMA_CERTIFICATE
              server: $KYMA_SERVER
          contexts:
          - name: xsk
            context:
              cluster: xsk
              user: xsk
          users:
          - name: xsk
            user:
              token: $KYMA_TOKEN" > $HOME/.kube/config
      - name: Export Kyma Host
        run: |
          export KYMA_API_SERVER=${{ secrets.KYMA_SERVER }}
          echo "KYMA_HOST=${KYMA_API_SERVER:12}" >> $GITHUB_ENV
      - name: Helm Upgrade Application Instance
        run: |
          helm repo add xsk https://www.xsk.io
          helm repo update
          helm upgrade --install xsk xsk/xsk \
          --set kyma.enabled=true \
          --set kyma.host=$KYMA_HOST \
          --set hana.enabled=true \
          --set hana.url='jdbc:sap://${{ secrets.HANA_URL }}/?encrypt=true&validateCertificate=false`' \
          --set hana.username=${{ secrets.HANA_USERNAME }} \
          --set hana.password='${{ secrets.HANA_PASSWORD }}' \
          --set persistentVolumeClaim.enabled=false \
          --set deployment.strategyType=RollingUpdate \
          --set application.image=${{secrets.DOCKER_REGISTRY}}/${{ github.event.inputs.applicationRepository }}:${{ github.event.inputs.applicationReleaseVersion }}
