name: Synchronize Content
on:
  workflow_dispatch
#   schedule:
#     - cron:  '0/5 * * ? *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_TOKEN}}
          ref: gh-pages
      - name: Sync Content
        run: |
          mkdir sync
          cd sync/
          git clone https://github.com/sap/xsk
          cd xsk/
          git checkout gh-pages
          cp -R * ../../
          cd ../..
          rm -rf sync/
      - name: Calculate Changes
        run: |
          git add .
          HAVE_CHANGES=$(git diff HEAD) >> $GITHUB_ENV
      - name: Commit and Push Changes
        if: ${{ env.HAVE_CHANGES != '' }}
        run: |
          git config user.name ${{secrets.GH_USER_NAME}}
          git config user.email ${{secrets.GH_USER_EMAIL}}
          git commit -m "Sync Content"
          git push origin gh-pages
          
