name: Get latest release version
on:
  workflow_dispatch
#   schedule:
#     - cron:  '0/5 * * ? *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_TOKEN}}
      - name: sync
        run: |
          mkdir sync
          cd sync/
          git clone https://github.com/sap/xsk
          cd xsk/
          git checkout -b gh-pages
          cp -R * ../../
          cd ../..
          rm -rf sync/
          git status
          git diff
          
