name: Synchronize Content
on:
  workflow_dispatch
#   schedule:
#     - cron:  '0/5 * * ? *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_TOKEN}}
          ref: gh-pages
      - name: Sync Content
        run: |
          mkdir sync
          cd sync/
          git clone https://github.com/sap/xsk
          cd xsk/
          git checkout gh-pages
          cp -R * ../../
          cd ../..
          rm -rf sync/
      - name: Git Config
        run: |
          git config user.name ${{secrets.GH_USER_NAME}}
          git config user.email ${{secrets.GH_USER_EMAIL}}
      - name: Calculate Changes
        run: |
          git add .
          HAVE_CHANGES=$(git diff HEAD) >> $GITHUB_ENV
      - name: Set Calculate Changes
        id: changes
        run: |
          if [ "$HAVE_CHANGES" == "" ]; then
            echo ::set-output name=havechanges::false
          else
            echo ::set-output name=havechanges::true
          fi
          echo "Have Changes"
          echo ${{ steps.changes.outputs.havechanges}}
      - name: Commit and Push Changes
        if: ${{ steps.changes.outputs.havechanges }}
        run: |
          git commit -m "Sync Content"
          git push origin gh-pages
          
